<?php

/*
 * phpMyEdit language file
 *
 * language: french (standard) 
 * encoding: iso-8859-1
 * date: 2002-02, 2002-11-07, 2002-12-29
 * authors:
 *   Dario <dartar@users.sourceforge.net>
 *   Kaid <kaid@fr.st>
 *   hbernard <hbernard@gynov.org>
 */

/* $Platon: phpMyEdit/lang/PME.lang.FR.inc,v 1.15 2004-12-27 20:14:29 nepto Exp $ */

return Array(
		'Add'           =>'Ajouter',
		'Copy'          =>'Copier',
		'Change'        =>'Modifier',
		'Delete'        =>'Supprimer',
		'View'      	=>'Afficher',
		'Prev'          =>'Pr&#233;c&#233;dent',
		'Next'          =>'Suivant',
		'First'         =>'D&#233;but',
		'Last'          =>'Fin',
		'Go to'         =>'Aller &agrave; ',
		'Page'          =>'Page',
		'Records'       =>'Enregistrements',
		'Save'          =>'Enregistrer',
		'More'          =>'Enregistrer et continuer',
		'Apply'         =>'Appliquer',
		'Cancel'        =>'Annuler',
		'Search'        =>'Rechercher',
		'Hide'          =>'Cacher',
		'Clear'         =>'Vider',
		'Query'         =>'Requ&#234;te',
		'Current Query'	=>'Requ&#234;te courante',
		'Sorted By'		=>'Tri',
		'ascending'		=>'croissant',
		'descending'	=>'d&#233;croissant',
		'hidden'		=>'cach&#233;',
		'of'            =>'/',		// untranslated
		'record added'  =>'Enregistrement ajout&#233;',
		'record changed'=>'Enregistrement modifi&#233;',
		'record deleted'=>'Enregistrement supprim&#233;',
		'Please enter'  =>'Entrez s\'il vous plaît',
		'months'	=> Array(
			'01'=>'Janvier',
			'02'=>'F&#233;vrier',
			'03'=>'Mars',
			'04'=>'Avril',
			'05'=>'Mai',
			'06'=>'Juin',
			'07'=>'Juillet',
			'08'=>'Août',
			'09'=>'Septembre',
			'10'=>'Octobre',
			'11'=>'Novembre',
			'12'=>'D&#233;cembre'),
		// phpMyEdit-report
		'Make report'			=> 'Make report',
		'Select fields'			=> 'Select fields',
		'Records per screen'	=> 'Records per screen',
		);

?>
