<?php
set_include_path(".".PATH_SEPARATOR."..");
require_once("inc/main.inc.php");
/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, check official documentation. It is available
 * online and also for download on phpMyEdit project management page:
 *
 * http://platon.sk/projects/main_page.php?project_id=5
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.6
 *       phpMyEdit.class.php core class: 1.188
 *            phpMyEditSetup.php script: 1.48
 *              generating setup script: 1.48
 */

PagePermission::verifyPagePermission( new PagePermission(PagePermission:: $CONSTRAINT_ENSEIGNANT_LOGGED));
$nomEns = SessionManager::getEnseignant()->getNomEnseignant();
$prenomEns = SessionManager::getEnseignant()->getPrenomEnseignant();
$idEns = SessionManager::getEnseignant()->getIdEnseignant();
$idStage=@$_GET['idStage'];

if (isset($_POST['mail'])&& isset($_POST['from'])){
	$FicheEtudiante = DBFicheStage::getRecords($idStage,"","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",$idEns);
	$FicheEtudiante[0]->sendMailFiche_suivi($_POST['mail'],$_POST['from']);
}
else {
 
 /****IMPRESSION****/
include("../impression.php");

echo "<center><h1>Espace enseignant $nomEns $prenomEns</h1></center>";
echo "<h2> Mailer une visite</h2><br/>";

//Creation de l'objet a partir de l idStage
$FicheEtudiante = DBFicheStage::getRecords($idStage,"","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",$idEns);

//enregistrement des informations
$nom_etu = $FicheEtudiante[0]->getNomEtudiant();
$prenom_etu=$FicheEtudiante[0]->getPrenomEtudiant();
$date_visite=$FicheEtudiante[0]->getDateVisiteStage();
$type_stage=$FicheEtudiante[0]->getLibelleTypeStage();
$intitule=$FicheEtudiante[0]->getIntituleStage();
$sujet=$FicheEtudiante[0]->getSujetStage();
$entreprise=$FicheEtudiante[0]->getRaisonSocialeEntreprise();
$nom_maitre = $FicheEtudiante[0]->getNomMaitreStage();
$prenom_maitre= $FicheEtudiante[0]->getPrenomMaitreStage();
$avis_etu=$FicheEtudiante[0]->getAvisEtudiantVisite();
$avis_maitre=$FicheEtudiante[0]->getAvisMaitreStageVisite();
$avis_tuteur=$FicheEtudiante[0]->getAvisTuteurVisite();
$correspondance=$FicheEtudiante[0]->getCorrespSujetTravailVisite();

//recapitulatif de la fiche de suivi
echo "<br/><table width='100%'>
 <td><th width='20%' align='center'> Nom</th><td>".$nom_etu."</td></tr>
 <td><th width='20%' align='center'> Prenom</th><td>".$prenom_etu."</td></tr>  
 <td><th width='20%' align='center'> Type de stage</th><td>".$type_stage."</td></tr> 
 <td><th width='20%' align='center'> Date de visite</th><td>".$date_visite."</td></tr>   
 <td><th width='20%' align='center'> Entreprise</th><td>".$entreprise."</td></tr>
 <td><th width='20%' align='center'> Intitule</th><td>".$intitule."</td></tr>
 <td><th width='20%' align='center'> Sujet stage</th><td>".$sujet."</td></tr>
 <td><th width='20%' align='center'> Nom tuteur</th><td>".$nom_maitre."</td></tr>
 <td><th width='20%' align='center'> Prenom tuteur</th><td>".$prenom_maitre."</td></tr>
 <td><th width='20%' align='center'> Avis etudiant</th><td>".$avis_etu."</td></tr>
 <td><th width='20%' align='center'> Avis ma&icirc;tre de stage</th><td>".$avis_maitre."</td></tr>
 <td><th width='20%' align='center'> Avis tuteur</th><td>".$avis_tuteur."</td></tr>
 <td><th width='20%' align='center'> Correspondance sujet - travail</th><td>".$correspondance."</td></tr>
</table><br/><br/>";

//affichage du formulaire, pour récupérer les adresses mails
echo "
<form method='post' action='mail_suivi.php?idStage=".$idStage."'>
<p>Veuillez saisir les adresses emails des personnes que vous souhaitez contacter en les s&eacute;parant par une virgule</p>
<textarea name='mail' rows='4' cols='45'></textarea>
<p>Veuillez saisir votre adresse mail</p>
<textarea name='from' rows='2' cols='45'></textarea><br/><br/>
<input type='submit' value='Envoyer' />
</form>";
}
?>

