<?php

set_include_path(".".PATH_SEPARATOR."..");
require_once("inc/main.inc.php");
require_once("inc/configPhpMyEdit.inc.php");
PagePermission::verifyPagePermission( new PagePermission(PagePermission::$CONSTRAINT_ADMIN_LOGGED));

/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, check official documentation. It is available
 * online and also for download on phpMyEdit project management page:
 *
 * http://platon.sk/projects/main_page.php?project_id=5
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.6
 *       phpMyEdit.class.php core class: 1.188
 *            phpMyEditSetup.php script: 1.48
 *              generating setup script: 1.48
 */

$opts['tb'] = 'fiche_stage';

// Name of field which is the unique key
$opts['key'] = 'id_stage';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'int';

// Sorting field(s)
$opts['sort_field'] = array('-promo_stage','nom_etudiant','prenom_etudiant');

// Number of records to display on the screen
// Value of -1 lists all records in a table
$opts['inc'] = 15;

// Options you wish to give the users
// A - add,  C - change, P - copy, V - view, D - delete,
// F - filter, I - initial sort suppressed
$opts['options'] = 'CV';

// Number of lines to display on multiple selection filters
$opts['multiple'] = '4';

// Navigation style: B - buttons (default), T - text links, G - graphic links
// Buttons position: U - up, D - down (default)
$opts['navigation'] = 'UB';

// Display special page elements
$opts['display'] = array(
	'form'  => true,
	'query' => true,
	'sort'  => true,
	'time'  => true,
	'tabs'  => true
);

// Set default prefixes for variables
$opts['js']['prefix']               = 'PME_js_';
$opts['dhtml']['prefix']            = 'PME_dhtml_';
$opts['cgi']['prefix']['operation'] = 'PME_op_';
$opts['cgi']['prefix']['sys']       = 'PME_sys_';
$opts['cgi']['prefix']['data']      = 'PME_data_';

/* Get the user's default language and use it if possible or you can
   specify particular one you want to use. Refer to official documentation
   for list of available languages. */
$opts['language'] = $_SERVER['HTTP_ACCEPT_LANGUAGE'];

/* Table-level filter capability. If set, it is included in the WHERE clause
   of any generated SELECT statement in SQL query. This gives you ability to
   work only with subset of data from table.
*/

$opts['filters'] = "promo_stage = ".DBConfig::getConfigValue("ANNEE PROMO");

/* Field definitions
   
Fields will be displayed left to right on the screen in the order in which they
appear in generated list. Here are some most used field options documented.

['name'] is the title used for column headings, etc.;
['maxlen'] maximum length to display add/edit/search input boxes
['trimlen'] maximum length of string content to display in row listing
['width'] is an optional display width specification for the column
          e.g.  ['width'] = '100px';
['mask'] a string that is used by sprintf() to format field output
['sort'] true or false; means the users may sort the display on this column
['strip_tags'] true or false; whether to strip tags from content
['nowrap'] true or false; whether this field should get a NOWRAP
['select'] T - text, N - numeric, D - drop-down, M - multiple selection
['options'] optional parameter to control whether a field is displayed
  L - list, F - filter, A - add, C - change, P - copy, D - delete, V - view
            Another flags are:
            R - indicates that a field is read only
            W - indicates that a field is a password field
            H - indicates that a field is to be hidden and marked as hidden
['URL'] is used to make a field 'clickable' in the display
        e.g.: 'mailto:$value', 'http://$value' or '$page?stuff';
['URLtarget']  HTML target link specification (for example: _blank)
['textarea']['rows'] and/or ['textarea']['cols']
  specifies a textarea is to be used to give multi-line input
  e.g. ['textarea']['rows'] = 5; ['textarea']['cols'] = 10
['values'] restricts user input to the specified constants,
           e.g. ['values'] = array('A','B','C') or ['values'] = range(1,99)
['values']['table'] and ['values']['column'] restricts user input
  to the values found in the specified column of another table
['values']['description'] = 'desc_column'
  The optional ['values']['description'] field allows the value(s) displayed
  to the user to be different to those in the ['values']['column'] field.
  This is useful for giving more meaning to column values. Multiple
  descriptions fields are also possible. Check documentation for this.
*/

$opts['fdd']['id_stage'] = array(
  'name'     => 'ID stage',
  'select'   => 'T',
  'options'  => 'AVCPDR', // auto increment
  'maxlen'   => 11,
  'default'  => '0',
  'sort'     => true
);
$opts['fdd']['libelle_type_stage'] = array(
  'name'     => 'Libelle type stage',
  'select'   => 'T',
  'maxlen'   => 255,
  'options'  => 'VC',
  'sort'     => true
);
$opts['fdd']['promo_stage'] = array(
  'name'     => 'Promo stage',
  'select'   => 'T',
  'maxlen'   => 11,
  'default'  => '0',
  'input'    => 'R',
  'sort'     => true
);
$opts['fdd']['nom_etudiant'] = array(
  'name'     => 'Nom etudiant',
  'select'   => 'T',
  'maxlen'   => 255,
  'input'    => 'R',
  'sort'     => true
);
$opts['fdd']['prenom_etudiant'] = array(
  'name'     => 'Prenom etudiant',
  'select'   => 'T',
  'maxlen'   => 255,
  'input'    => 'R',
  'sort'     => true
);
$opts['fdd']['raison_sociale_entreprise'] = array(
  'name'     => 'Raison sociale',
  'select'   => 'T',
  'maxlen'   => 255,
  'sort'     => true
);
$opts['fdd']['nom_maitre_stage'] = array(
  'name'     => 'Nom maitre stage',
  'select'   => 'T',
  'maxlen'   => 255,
  'options'  => 'VC',
  'sort'     => true
);
$opts['fdd']['prenom_maitre_stage'] = array(
  'name'     => 'Prenom maitre stage',
  'select'   => 'T',
  'maxlen'   => 255,
  'options'  => 'CV',
  'sort'     => true
);
$opts['fdd']['nom_signataire_stage'] = array(
  'name'     => 'Nom signataire stage',
  'select'   => 'T',
  'maxlen'   => 255,
  'options'  => 'CV',
  'sort'     => true
);
$opts['fdd']['prenom_signataire'] = array(
  'name'     => 'Prenom signataire',
  'select'   => 'T',
  'maxlen'   => 255,
  'options'  => 'CV',
  'sort'     => true
);
$opts['fdd']['intitule_stage'] = array(
  'name'     => 'Intitule stage',
  'select'   => 'T',
  'maxlen'   => 255,
  'sort'     => true
);
$opts['fdd']['sujet_stage'] = array(
  'name'     => 'Sujet stage',
  'select'   => 'T',
  'maxlen'   => 65535,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
  'options'  => 'LCH',
  'options'  => 'VC',
  'sort'     => true
);
$opts['fdd']['techno_stage'] = array(
  'name'     => 'Technologie Stage',
  'select'   => 'T',
  'maxlen'   => 255,
  'options'  => 'CV',
  'sort'     => true
);
$opts['fdd']['desc_techno_stage'] = array(
  'name'     => 'Descriptif Techno Stage',
  'select'   => 'T',
  'maxlen'   => 65535,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
  'options'  => 'LCH',
  'options'  => 'VC',
  'sort'     => true
);
$opts['fdd']['date_debut_stage'] = array(
  'name'     => 'Date debut stage',
  'select'   => 'T',
  'maxlen'   => 10,
  'options'  => 'LCH',
  'options'  => 'V',
  'sort'     => true
);
$opts['fdd']['date_fin_stage'] = array(
  'name'     => 'Date fin stage',
  'select'   => 'T',
  'maxlen'   => 10,
  'options'  => 'LCH',
  'options'  => 'V',
  'sort'     => true
);
$opts['fdd']['etat_stage'] = array(
  'name'     => 'Etat stage',
  'select'   => 'T',
  'maxlen'   => 24,
  'values'   => array(
                  'En attente de validation', 
				  'Validee', 
				  'Refusee', 
				  'Signature Entreprise', 
				  'Signature Universite', 
				  'Terminee'),
  'default'  => 'En attente de validation',
  'sort'     => true
);
$opts['fdd']['date_creation_suivi'] = array(
  'name'     => 'Date creation suivi',
  'select'   => 'T',
  'maxlen'   => 19,
  'options'  => 'LCH',
  'options'  => 'V',
  'sort'     => true
);
$opts['fdd']['date_derniere_modif_suivi'] = array(
  'name'     => 'Date derniere modif suivi',
  'select'   => 'T',
  'maxlen'   => 19,
  'options'  => 'LCH',
   'options'  => 'V',
  'sort'     => true
);
$opts['fdd']['date_validation_suivi'] = array(
  'name'     => 'Date validation suivi',
  'select'   => 'T',
  'maxlen'   => 19,
  'options'  => 'LCH',
   'options'  => 'V',
  'sort'     => true
);
$opts['fdd']['date_signature_entreprise_suivi'] = array(
  'name'     => 'Date signature entreprise',
  'select'   => 'T',
  'maxlen'   => 19,
  'options'  => 'LCH',
   'options'  => 'V',
  'sort'     => true
);
$opts['fdd']['date_signature_universite_suivi'] = array(
  'name'     => XHTMLBuilder::GetText('Date signature université'),
  'select'   => 'T',
  'maxlen'   => 19,
  'options'  => 'LCH',
   'options'  => 'V',
  'sort'     => true
);
$opts['fdd']['date_finale_suivi'] = array(
  'name'     => 'Date finale suivi',
  'select'   => 'T',
  'maxlen'   => 19,
  'options'  => 'LCH',
  'options'  => 'V',
  'sort'     => true
);
$opts['fdd']['date_refus_suivi'] = array(
  'name'     => 'Date refus suivi',
  'select'   => 'T',
  'maxlen'   => 19,
  'options'  => 'LCH',
   'options'  => 'V',
  'sort'     => true
);
$opts['fdd']['motif_refus_stage_suivi'] = array(
  'name'     => 'Motif refus stage suivi',
  'select'   => 'T',
  'maxlen'   => 65535,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
  'options'  => 'LCH',
   'options'  => 'V',
  'sort'     => true
);
// Now important call to phpMyEdit
require_once 'phpMyEdit/phpMyEdit.class.php';
new phpMyEdit($opts);

?>